app/urls.py
from django.urls import path
from . import views
from django.contrib import admin


app_name = 'app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    path('', views.home, name='home'),
    
    path('marketplace/', views.placements, name='placements'),
    path('marketplace/<placement_slug>/', views.placement_detail, name='placement-detail'),

    path('my-bids/', views.bid_summary, name='bid-summary' ),
    path('confirm-bids/', views.confirm_bids, name='confirm-bids'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('about/', views.about, name='about'),

    path('admin/', admin.site.urls)
]

bidding_system/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app'))
]

app/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
# Create your models here.

class Company(models.Model):
    """
    Simply contains company details, referenced by Placement model
    """

    company_name = models.CharField(max_length=255)
    company_address = models.CharField(max_length=255)
    company_description = models.TextField(default="There is currently no description available for this company.")

    company_created = models.DateTimeField(auto_now_add=True)
    company_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.company_name


class Placement(models.Model):
    """
    A placement allows investors to bid on company capital raise
    """

    placement_title = models.CharField(max_length=255)
    placement_slug = models.SlugField()
    placement_company = models.ForeignKey(Company, on_delete=models.CASCADE)


    placement_created = models.DateTimeField(auto_now_add=True)
    placement_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.placement_title


class Bid(models.Model):
    """
    The bid, synonmous with 'order'
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bid_status = models.BooleanField(default=False)

    bid_created = models.DateTimeField(auto_now_add=True)
    bid_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} -{}'.format(self.user, self.bid_status)


class PlacementBid(models.Model):
    """
    The junction table for placement and bid models/tables. Contains every instance of a bid for a placement
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    placement = models.ForeignKey(Placement, on_delete=models.CASCADE)
    bid  = models.ForeignKey(Bid, on_delete=models.CASCADE)
    offer = models.IntegerField()
    shares = models.IntegerField()
    confirmed = models.BooleanField(default=False)
    
    placementbid_created = models.DateTimeField(auto_now_add=True)
    placementbid_modified = models.DateTimeField(auto_now=True)

    class Meta: 
        ordering = ['-placementbid_modified'] 

    def __str__(self):
        return '{} - {} - {}'.format(self.shares, self.offer, self.user)

app/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class CustomRegisterForm(UserCreationForm):

    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomRegisterForm
from .models import Placement, PlacementBid, Bid, Company
from django.contrib.auth.models import User
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Sum, Avg, Count


def register(request):
    if request.method == 'POST':
        form = CustomRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('app:login')
    else:
        form = CustomRegisterForm()
    
    context = {'form': form}

    return render(request, 'register.html', context)


def login(request):
    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth_login(request, user)
            return redirect('app:home')
        else:
            return render(request, 'login.html') 
            
    else:
        return render(request, 'login.html') 


def home(request):

    return render(request, 'home.html')


@login_required
def logout(request):
    auth_logout(request)
    return redirect('app:login')


@login_required
def placements(request):
    
    all_placements = Placement.objects.all()

    paginator = Paginator(all_placements, 18)
    page = request.GET.get('page')
    placements = paginator.get_page(page)

    context = {'placements': placements}

    return render(request, 'placements.html', context)


@login_required
def placement_detail(request, placement_slug):

    placement = get_object_or_404(Placement, placement_slug=placement_slug)

    if request.method == 'POST':
        submitted_quantity = request.POST.get('quantity')
        submitted_amount = request.POST.get('amount')

        # Create or store Bid object based on conditional
        bid_queryset = Bid.objects.filter(user=request.user, bid_status=False)
        
        if bid_queryset.exists():
            bid = bid_queryset[0]
        else:
            bid = Bid.objects.create(user=request.user)
        
        # Create PlacementBid given the above objects
        placement_bid = PlacementBid.objects.create(user=request.user, 
                                                    placement=placement, 
                                                    bid=bid,
                                                    offer=submitted_amount,
                                                    shares=submitted_quantity)
        return redirect('app:home')

    context = {'placement': placement}

    return render(request, 'placement_detail.html', context)


@login_required
def bid_summary(request):

    bids = PlacementBid.objects.filter(user=request.user)

    context = {'bids': bids}

    return render(request, 'bid-summary.html', context)



@login_required
def confirm_bids(request):

    bids_queryset = PlacementBid.objects.filter(user=request.user, confirmed=False)
    
    if bids_queryset.exists():

        # First get the order ID
        bid_id = bids_queryset[0].bid.id

        # Update PlacementBid Objects confirmed flag
        for bid in bids_queryset:
            bid.confirmed = True
            bid.save()
        
        # Update the Bid object status
        bid = Bid.objects.filter(id=bid_id)[0]
        bid.bid_status = True
        bid.save()

    return redirect('app:bid-summary')


def about(request):

    return render(request, 'about.html')


@login_required
def dashboard(request):
    
    # Get tile data
    total_companies = Company.objects.count()
    total_users = User.objects.count()
    total_placements = Placement.objects.count()
    #total_offers = PlacementBid.objects.aggregate(Sum('offer'))['offer__sum']
    # total_offers_k = total_offers // 1000
    
    # Get aggregate data
    top_5 = PlacementBid.objects\
                    .values('placement__placement_company__company_name', 'offer')\
                    .annotate(Sum('offer'))\
                    .order_by('-offer')[:5]

    top_5_offer_names = [item['placement__placement_company__company_name'] for item in top_5]
    top_5_offer_names = [name[:8] + '...' for name in top_5_offer_names]
    top_5_offer_values = [item['offer'] for item in top_5]

    # Store context
    context = {'total_companies':total_companies,
                'total_users':total_users,
                'total_placements':total_placements,
                # 'total_offers':total_offers_k,
                'top_5_offer_names':top_5_offer_names,
                'top_5_offer_values':top_5_offer_values}

    return render(request, 'dashboard.html', context)

templates/about.html
{% extends 'base.html' %} {% block content %} {% include 'nav.html' %}

<section class="section">
    <section class="container">

        <article class="card">
            <div class="card-content">
                <h4>About</h4>
                <p class="custom-font-1">This is a Cloud Application which uses Amazon Web servies like the EC2, S3 buckets.This application is a bidding website where we can bid for a role.</p>
</div>
        </article>
        <article class="card">
            <div class="card-content">
                <h4>Available Routes</h4>
                <ul class="collection custom-font-1">
                    <li class="collection-item"><span class="chip">/</span> The home page. Contains news.</li>
                    <li class="collection-item"><span class="chip">about/</span> Holds details about the application.</li>
                    <li class="collection-item"><span class="chip">register/</span> Allows users to register an account</li>
                    <li class="collection-item"><span class="chip">login/</span> Allows users to login to an account</li>
                    <li class="collection-item"><span class="chip">logout/</span> Allows users to logout and clear their session</li>

                    <li class="collection-item"><span class="chip">marketplace/</span> Listing of placements from various companies.</li>

                    <li class="collection-item"><span class="chip">marketplace/slug/</slug></span> Detailed view for a placement within the marketplace.</li>
                    <li class="collection-item"><span class="chip">my-bids/</span> User scope bid summary for available placements.</li>
                    <li class="collection-item"><span class="chip">dashboard/</span> Basic analytics and animated charts for the database.</li>

                </ul>
            </div>
        </article>


        <article class="card">
            <div class="card-content">
                <h4>Features and specs</h4>
                <ul class="collection custom-font-1">
                    <li class="collection-item">Authentication system - users can login, register and logout, passwords are secure</li>
                    <li class="collection-item ">Application is hosted in Cloud</li>
                    <li class="collection-item">Dashboard include dynamic and animated charts to draw insights from database.</li>
                    <li class="collection-item">S3 buckets is Used for storing and retriving the images</li>
                    <li class="collection-item">The application uses EC2 instance and is hosted on AWS</li>
                </ul>
            </div>
        </article>

    </section>
</section>

{% include 'footer.html' %} {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <link href="https://fonts.googleapis.com/css?family=Literata|Raleway|Montserrat|Nunito&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    
    <title>Bidding System</title>

    <style>
      p {
        margin-top: 0.5rem !important;
        margin-bottom: 0.5rem!important;
      }

      img {
        margin-top: 1em;
        padding: 4%;
      }

      .custom-font-1 {
        font-family: 'Literata', serif;
      } 

      h1, h2, h3, h4, h5, h6 {
        margin-top: .5em !important;
        font-family: 'Nunito', sans-serif;
        font-weight: bold;
      }

      body {
        display: flex;
        min-height: 100vh;
        flex-direction: column;
      }

      main {
        flex: 1 0 auto;
      }
        
      input:focus {
        border-bottom: 1px solid deeppink !important;
        box-shadow: 0 1px 0 0 deeppink !important;
      }


      /* ----------------------------------------------
 * Generated by Animista on 2019-7-21 13:37:41
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

.fade-in {
	-webkit-animation: fade-in 1s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: fade-in 1s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}



    </style>
</head>
<body class="grey lighten-4">
    {% block content %}
    {% endblock content %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
    document.addEventListener('DOMContentLoaded', function(){
      var elems = document.querySelectorAll('.sidenav');
      var instances = M.Sidenav.init(elems);
    })
    </script>
</body>
</html>

templates/bid-summary.html
{% extends 'base.html' %}

{% block content %}
{% include 'nav.html' %}

<section class="section">
    <section class="container">
        <div class="card">
            <div class="card-content">
                <h4>Your bid summary</h4>
                <table class="table responsive-table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Bid status</th>
                            <th>Company Name</th>
                            <th>Timestamp</th>
                            <th>$ Bidded</th>
                            <th>no. Shares</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for b in bids %}
                            <tr>
                                <td>{{ b.id }}</td>
                                <td>{% if b.confirmed %}<span class="chip">Confirmed</span>{%else%} <span class="chip indigo darken-2 white-text">Unconfirmed</span>       {%endif%}</td>
                                <td>{{ b.placement.placement_company }}</td>
                                <td>{{ b.placementbid_created }}</td>
                                <td>{{ b.offer}}</td>
                                <td>{{ b.shares}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <a href="{% url 'app:confirm-bids' %}" style="margin-top: 1rem;" class="btn waves-light waves-effect pink">Confirm Bids</a>
            </div>
        </div>

    </section>
</section>

{% include 'footer.html' %}
{% endblock content %}

templates/footer.html
<footer class="page-footer indigo darken-2">
        <!-- <div class="footer-copyright pink lighten-1"> -->
          <div class="container center custom-font-1">
          © 2022 Cloud @ CSUEB
          </div>
        <!-- </div> -->
      </footer>
          

templates/home.html
{% extends 'base.html' %} {% block content %} {% include 'nav.html' %} {% load static %}

<section class="section">
    <section class="container">
        {% if user.is_authenticated == False %}
        <div class="card z-depth-2">
            <div class="card-content">
                <h5>Notice</h5>
                <p class="custom-font-1">You must have a registered account and be logged in, in order to view and place bids within our marketplace.</p>
            </div>
        </div>
        {% endif %}

        <div class="card z-depth-2">
            <div class="card-content">
                
                <h5>Bidding Place</h5>

                <p class="custom-font-1">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minus ullam, odit iure incidunt inventore praesentium consectetur in animi rerum labore ab esse ex deleniti deserunt quaerat sapiente sunt quis a?</p>
                <a href="{% url 'app:placements' %}" class="btn waves-effect waves-light pink" style="margin-top: 1rem;">
                        <i class="material-icons left">store</i>visit the market</a>
                <img class="responsive-img fade-in" src="https://biddingbucket.s3.amazonaws.com/dashboard.jpg" alt="">
            </div>
        </div>


        <div class="card z-depth-2">
            <div class="card-content">
                <h5>
                    News (April)
                </h5>
                <h4 class="custom-font-1">Major Aspects of Software Cost Estimation</h4>
                <p class="custom-font-1">It is well-known that software engineering is at the lead of the services
                    that use outsourcing and outside contractors. Statistics say that the
                    global contract value ranges from $63.5 billion to $159.1 billion and it
                    includes software products development services as well.
                    So, estimation of your software product development plays a crucial
                    role in your business planning and you should choose an agency or a
                    contractor with the right approach for estimation of a software project.</p>
                <img class="responsive-img fade-in" src="https://biddingbucket.s3.amazonaws.com/news.jpg" alt="">
            </div>
        </div>

        <div class="card z-depth-2">
            <div class="card-content">
                <h5>
                    News (May)
                </h5>
                <h4 class="custom-font-1">Popular Codeless Open Source Testing Tools</h4>
                <p class="custom-font-1">Programming languages have always been an integral part of
                    automation testing, automation testers, frameworks and even job
                    descriptions. If a legacy project is already tested using Java, the
                    company finds people with expertise in Java for that project. Similarly,
                    if it is a new project and you have to start testing from scratch, the first
                    thing you take a vote on is the most common language known to your
                    team.
                    If nobody knows Python, you probably wouldn’t waste your time
                    training them in it. This process is followed again when choosing a
                    framework for testing. If the decided language is Java, you need a test
                    automation framework supporting Java. Also, vice-versa is true for a
                    legacy project.</p>
                <img class="responsive-img fade-in" src="https://biddingbucket.s3.amazonaws.com/news-2.jpg" alt="">
            </div>
        </div>

        <!-- <div class="card z-depth-2">
            <div class="card-content">
                <h5>
                    News (May)
                </h5>
                <p class="custom-font-1">Sunt excepteur do culpa velit consequat deserunt aute deserunt. Voluptate sit cillum cillum nostrud. Esse duis eu ut minim ad excepteur consequat amet est. Ullamco Lorem tempor excepteur veniam do ea incididunt anim eu non est eu voluptate
                    adipisicing.</p>
                <p class="custom-font-1"><br>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illum culpa neque rerum sit maiores blanditiis et, dolorem labore, architecto harum explicabo optio nemo quo aut. Pariatur cum laboriosam id vel.</p>
                <p class="custom-font-1"><br>Velit et anim ea occaecat mollit enim commodo fugiat nisi anim fugiat. Fugiat ut occaecat consequat qui ex sunt proident esse aliquip adipisicing Lorem. Ullamco reprehenderit cupidatat ipsum non voluptate magna occaecat ullamco veniam
                    excepteur. Minim duis nostrud ex enim laboris minim irure dolore dolor aute occaecat dolor. Cillum do labore dolor consectetur fugiat enim voluptate. Sunt esse commodo laboris ut ipsum tempor nisi amet id anim aliqua aliquip fugiat.</p>
                <img class="responsive-img fade-in" src="{% static 'lycs-architecture-744230-unsplash.jpg' %}" alt="">
            </div>
        </div> -->

    </section>
</section>

{% include 'footer.html' %} {% endblock content %}

templates/login.html
{% extends 'base.html' %} {% block content %}
<main>
    <section class="section">
        <section class="container">
            <div class="row">
                <div class="col l8 m12 s12">
                    <div class="card">
                        <div class="card-content">
                            <form action="" method="POST" class="form">
                                {% csrf_token %}
                                <h5>Login page</h5>
                                <div class="input-field">
                                    <label for="" class="label">
                                        Username
                                    </label>
                                    <input type="text" name="username">
                                </div>
                                <div class="input-field">
                                    <label for="" class="label">
                                        Password
                                    </label>
                                    <input type="password" name="password">
                                </div>
                                <div class="input-field">
                                    <button style="margin-top: 1rem;" class="btn waves-effect waves-light pink" type="submit">Login</button>
                                </div>
                                <p>Don't have an account? click <a href="{% url 'app:register' %}" style="margin-top: 1rem;" type="a">here</a> to register.</p>
                                <p>Don't have time to sign up? Use the guest account credentials below.</p>
                                <p class="chip">username: 'dc' password: '1'</p>
                            </form>
                        </div>
                    </div>

                </div>
            </div>

        </section>

    </section>
</main>
{% include 'footer.html' %} {% endblock content %}

templates/nav.html
<nav>
<div class="nav-wrapper indigo darken-2">
    <div class="container">
    <!-- <a href="{% url 'app:home' %}" class="brand-logo" style="font-size: 1.3rem;">
       <strong>BIDDING PLATFORM</strong></a> -->
    <a href="#" data-target="mobile-demo" class="sidenav-trigger waves-effect waves-light"><i class="material-icons">menu</i></a>
    <ul class="left hide-on-med-and-down">
            <li><a href="{% url 'app:home' %}"><i class="material-icons">home</i></a></li>
        <li><a href="{% url 'app:placements' %}"><i class="material-icons">store</i></a></li>
        <li><a href="{% url 'app:bid-summary' %}"><i class="material-icons">view_list</i></a></li>
        <li><a href="{% url 'app:about' %}"><i class="material-icons">help</i></a></li>
        <li><a href="{% url 'app:dashboard' %}"><i class="material-icons">insert_chart</i></a></li>
        
    </ul>

    <ul class="right hide-on-med-and-down">
            {% if user.is_authenticated %}
            <li><a class="btn-small waves-effect waves-light grey darken-4" href="{% url 'app:logout' %}">Logout</a></li>
            <li>Logged in as <strong>{{ user.username }}</strong></li>
        {% else %}
        <li>
            <a class="btn-small waves-effect waves-light pink" href="{% url 'app:register' %}">
                Register
            </a>
            </li>
        <li>
            <a class="btn-small waves-effect waves-light pink" href="{% url 'app:login' %}">
                Login
            </a>
        </li>
        {% endif %}
    </ul>
</div>
</div>
</nav>

<ul class="sidenav" id="mobile-demo">
    <li><a href="{% url 'app:home' %}"><i class="material-icons">home</i>Home</a></li>
    <li><a href="{% url 'app:placements' %}"><i class="material-icons">store</i>Marketplace</a></li>
    <li><a href="{% url 'app:bid-summary' %}"><i class="material-icons">view_list</i>My Bids</a></li>
    <li><a href="{% url 'app:about' %}"><i class="material-icons">assignment</i>About</a></li>
    <li><a href="{% url 'app:dashboard' %}"><i class="material-icons">insert_chart</i>Analytics</a></li>
    {% if user.is_authenticated %}
        <li><a class="btn-small waves-effect waves-light grey darken-4" href="{% url 'app:logout' %}">Logout</a></li>
    {% else %}
    <li><a class="btn-small waves-effect waves-light pink" href="{% url 'app:register' %}">
        Register</a>
    </li>
    <li><a class="btn-small waves-effect waves-light pink" href="{% url 'app:login' %}">
        Login</a>
    </li>
    {% endif %}
</ul>

templates/placements.html
{% extends 'base.html' %}

{% block content %}
{% include 'nav.html' %}

              
{% load static %}

<section class="section">
    <section class="container">
        
            <div class="col s12">
                    <div class="card">
                            <div class="card-content">
                                <h4>Welcome to the marketplace</h4>
                                <p>Explore placements by various listed companies</p>
                                <img src="https://biddingbucket.s3.amazonaws.com/bid.jpg" alt="" class="responsive-img fade-in">
                            </div>
                        </div>
            </div>

            <div class="card">
                <div class="card-content">
                        <table class="table responsive-table">
                                <thead>
                                    <tr>
                              
                                        <th>Placement Desc</th>
                                        <th>Company</th>
                                        <th>Added</th>
                                        <th>Modified</th>
                                        <th>View Details</th>
                                    </tr>
                                </thead>
                
                                <tbody>
                                        {%for p in placements %}
                                        <tr>
                             
                                            <td>{{ p.placement_title }}</td>
                                            <td><span class="chip indigo white-text">{{ p.placement_company }}</span></td>
                                            <td>{{ p.placement_created }}</td>
                                            <td>{{ p.placement_modified }}</td>
                                            <td><a href="{% url 'app:placement-detail' p.placement_slug %}" style="margin-top: 1rem;" class="btn pink waves-effect waves-light">View Details</a></td>
                                        </tr>
                                        {% endfor %}
                                </tbody>
                            </table>

                            <ul class="pagination center">
                                {% if placements.has_previous %}
                                <li class="waves-effect"><a href="?page={{placements.previous_page_number}}">{{ placements.previous_page_number}}</a></li>
                                {% endif %}

                                <li class="active indigo"><a href="#!">{{placements.number}}</a></li>
                               
                                {% if placements.has_next %}
                                <li class="waves-effect"><a href="?page={{placements.next_page_number}}">{{ placements.next_page_number}}</a></li>
                                {% endif %}
                            </ul>
                                            
                </div>
            </div>

    </section>
</section>

{% include 'footer.html' %}
{% endblock content %}

templates/register.html
{% extends 'base.html' %} {% block content %}
<main>
    <section class="section">
        <section class="container">
            <div class="row">
                <div class="col l12 s12">
                    <div class="card">
                        <div class="card-content">
                            <form action="" method="POST" class="form">
                                {% csrf_token %}
                                <h5>Registration page</h5>
                                {{ form.as_p }}
                                <div class="center">
                                    <button style="margin-top: 1rem;" class="btn pink waves-effect waves-light" type="submit">Create Account</button>
                                </div>
                                <a href="{% url 'app:home' %}" style="margin-top: 1rem;">Go back to home page.</a>

                            </form>
                            
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>
</main>
{% include 'footer.html' %} {% endblock content %}